name: sasadasalwo
favicon: null
layout_spectrum: 0.44472328084520996
typography_spectrum: 0.5197856738232076
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6726433364674449
  lightness: 0.8050425495021045
  saturation: 0.02833968447521329
  rhythmicContrast: 0.11184052214957774
purpose: []
