name: sasadasalwo
favicon: null
layout_spectrum: 0.44472328084520996
typography_spectrum: 0.18936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a26216'
    - '#ffa32a'
    - '#222d2c'
    - '#fffcd9'
    - '#76a583'
  brandStrength: 0.6726433364674449
  lightness: 0.8050425495021045
  saturation: 0.02833968447521329
  rhythmicContrast: 0.11184052214957774
purpose: []
